export enum ItemTypes {
  LINEAR_CONTAINER = 'LINEAR_CONTAINER',
  LAYER_CONTAINER = 'LAYER_CONTAINER',
  IMAGE = 'IMAGE',
  TEXT = 'TEXT',
  SEPARATOR = 'SEPARATOR',
  LINK = 'LINK',
  SAVE = 'SAVE',
  LIKE = 'LIKE',
  COMMENT = 'COMMENT',
  USER_INFORMATIONS = 'USER_INFORMATIONS',
  POST_TIME = 'POST_TIME',
  SHARE = 'SHARE',
}
